[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"

[[redirects]]
  from = "/api/*"
  to = "https://vajraxsentina-i7r5.onrender.com/api/:splat"
  status = 200
  force = true

