import asyncio
import re
import socket
import urllib.parse
from typing import Dict, Any, List, Optional
from datetime import datetime, timezone
import httpx

from app.core.ssrf import validate_and_normalize_target_url

class TargetDiagnosticsEngine:
    """Comprehensive target connectivity, DNS resolution, SSL, and WAF blocking diagnostic engine."""
    
    WAF_SIGNATURES = {
        "Cloudflare": [
            {"header": "server", "pattern": r"cloudflare"},
            {"header": "cf-ray", "pattern": r".+"},
            {"header": "cf-mitigated", "pattern": r".+"},
            {"body": r"attention required! \| cloudflare"},
            {"body": r"clouflare-nginx"}
        ],
        "AWS WAF": [
            {"header": "x-amzn-errortype", "pattern": r".+"},
            {"body": r"awswaf"},
            {"body": r"request blocked by aws waf"}
        ],
        "Akamai WAF": [
            {"header": "server", "pattern": r"akamaighost|akamai"},
            {"header": "x-akamai-request-id", "pattern": r".+"},
            {"header": "x-akamai-transformed", "pattern": r".+"},
            {"header": "x-akamai-session-info", "pattern": r".+"},
            {"body": r"access denied.*akamai|akamaiedge|reference\s*#[0-9a-f\.]+"}
        ],
        "Imperva / Incapsula": [
            {"header": "x-cdn", "pattern": r"incapsula"},
            {"header": "set-cookie", "pattern": r"incap_ses_|visid_incap_"},
            {"body": r"incapsula incident ID"}
        ],
        "ModSecurity": [
            {"header": "server", "pattern": r"mod_security|modsecurity"},
            {"body": r"this error was generated by mod_security"},
            {"body": r"media type not acceptable"}
        ],
        "Datadome": [
            {"header": "set-cookie", "pattern": r"datadome="},
            {"header": "x-datadome", "pattern": r".+"},
            {"body": r"datadome"}
        ],
        "F5 BIG-IP ASM": [
            {"header": "set-cookie", "pattern": r"^TS[0-9a-f]{8}="},
            {"header": "server", "pattern": r"big-ip|bigip"}
        ],
        "Sucuri WAF": [
            {"header": "x-sucuri-id", "pattern": r".+"},
            {"header": "server", "pattern": r"sucuri"}
        ]
    }

    async def analyze_target(self, target_url: str, custom_headers: Optional[Dict[str, str]] = None) -> Dict[str, Any]:
        result = {
            "target_url": target_url,
            "normalized_url": "",
            "is_valid_url": False,
            "ssrf_allowed": False,
            "validation_message": "",
            "hostname": "",
            "scheme": "",
            "port": 80,
            "dns_resolved": False,
            "ip_addresses": [],
            "tcp_reachable": False,
            "http_reachable": False,
            "status_code": 0,
            "response_time_ms": 0,
            "final_url": "",
            "page_title": "",
            "server_header": "",
            "waf_detected": False,
            "waf_name": "None",
            "blocking_status": "UNKNOWN",
            "blocking_reason": "",
            "recommendations": [],
            "headers_summary": {}
        }

        # 1. SSRF & URL Normalization
        is_valid, norm_url, reason = validate_and_normalize_target_url(target_url)
        result["normalized_url"] = norm_url
        result["is_valid_url"] = is_valid
        result["ssrf_allowed"] = is_valid
        result["validation_message"] = reason

        if not is_valid:
            result["blocking_status"] = "BLOCKED_SSRF_OR_INVALID"
            result["blocking_reason"] = f"Target URL failed safety validation: {reason}"
            result["recommendations"].append("Provide a valid public HTTP or HTTPS web application URL.")
            return result

        parsed = urllib.parse.urlparse(norm_url)
        hostname = parsed.hostname or "unknown"
        scheme = parsed.scheme or "https"
        port = parsed.port or (443 if scheme == "https" else 80)

        result["hostname"] = hostname
        result["scheme"] = scheme
        result["port"] = port

        # 2. DNS Resolution Diagnostic
        try:
            addr_info = socket.getaddrinfo(hostname, port, socket.AF_UNSPEC, socket.SOCK_STREAM)
            ip_list = list(set([item[4][0] for item in addr_info if item[4]]))
            result["dns_resolved"] = len(ip_list) > 0
            result["ip_addresses"] = ip_list
        except Exception as dns_err:
            result["dns_resolved"] = False
            result["blocking_status"] = "DNS_RESOLUTION_FAILED"
            result["blocking_reason"] = f"Unable to resolve hostname '{hostname}': {str(dns_err)}"
            result["recommendations"].append("Check domain DNS A/AAAA records or verify spelling.")
            return result

        # 3. TCP Port Connectivity Test
        tcp_ok = await self._test_tcp_connection(hostname, port)
        result["tcp_reachable"] = tcp_ok
        if not tcp_ok:
            result["blocking_status"] = "TCP_PORT_UNREACHABLE"
            result["blocking_reason"] = f"Port {port} on target host '{hostname}' timed out or rejected connection."
            result["recommendations"].append(f"Ensure target firewall allows inbound traffic on port {port}.")
            return result

        # 4. HTTP/HTTPS Application Probe & WAF Diagnostic
        req_headers = {
            "User-Agent": "Sentina-DAST-Scanner/1.0 (Security Assessment Engine)",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
        }
        if custom_headers:
            req_headers.update(custom_headers)

        start_t = datetime.now(timezone.utc)
        try:
            async with httpx.AsyncClient(
                headers=req_headers,
                timeout=12.0,
                follow_redirects=True,
                verify=False
            ) as client:
                resp = await client.get(norm_url)
                end_t = datetime.now(timezone.utc)
                duration_ms = int((end_t - start_t).total_seconds() * 1000)

                result["http_reachable"] = True
                result["status_code"] = resp.status_code
                result["response_time_ms"] = duration_ms
                result["final_url"] = str(resp.url)
                
                resp_headers = dict(resp.headers)
                result["server_header"] = resp_headers.get("server", "")
                result["headers_summary"] = {k: v for k, v in resp_headers.items() if k.lower() in [
                    "server", "content-type", "via", "x-powered-by", "cf-ray", 
                    "x-amzn-errortype", "strict-transport-security", "content-security-policy", "set-cookie"
                ]}

                # Extract title
                body_text = resp.text[:10000]
                title_m = re.search(r'<title[^>]*>(.*?)</title>', body_text, re.IGNORECASE | re.DOTALL)
                result["page_title"] = title_m.group(1).strip()[:150] if title_m else ""

                # 5. WAF & Blocking Signature Matching
                waf_detected, waf_name = self._detect_waf_signatures(resp_headers, body_text)
                result["waf_detected"] = waf_detected
                result["waf_name"] = waf_name

                # Determine Blocking Status
                if resp.status_code == 403 or resp.status_code == 406:
                    result["blocking_status"] = "WAF_BLOCKED" if waf_detected else "HTTP_403_FORBIDDEN"
                    result["blocking_reason"] = f"Target returned HTTP {resp.status_code} ({'WAF Block: ' + waf_name if waf_detected else 'Access Forbidden'})."
                    result["recommendations"].append(
                        f"{waf_name if waf_detected else 'Target WAF/Server'} is actively blocking automated probes. Whitelist Sentina Scanner IP or provide a valid Authorization Header in DAST settings."
                    )
                elif resp.status_code == 429:
                    result["blocking_status"] = "RATE_LIMITED"
                    result["blocking_reason"] = "Target returned HTTP 429 (Too Many Requests / Rate Limited)."
                    result["recommendations"].append("Reduce scan policy depth to 'Safe' or adjust scanner concurrency.")
                elif resp.status_code in (401, 407):
                    result["blocking_status"] = "AUTH_REQUIRED"
                    result["blocking_reason"] = f"Target requires authentication (HTTP {resp.status_code})."
                    result["recommendations"].append("Provide an Authorization Header or Bearer token under Target Options.")
                elif resp.status_code >= 500:
                    result["blocking_status"] = "SERVER_ERROR"
                    result["blocking_reason"] = f"Target application error (HTTP {resp.status_code})."
                    result["recommendations"].append("Verify server health or backend service status.")
                else:
                    result["blocking_status"] = "CLEAR"
                    result["blocking_reason"] = f"Target is fully reachable and accepting traffic (HTTP {resp.status_code}, {duration_ms} ms)."
                    if waf_detected:
                        result["recommendations"].append(f"Note: {waf_name} detected in headers, but target returned HTTP {resp.status_code} OK.")
                    else:
                        result["recommendations"].append("Target is ready for DAST vulnerability assessment.")

        except httpx.TimeoutException:
            result["blocking_status"] = "TIMEOUT"
            result["blocking_reason"] = f"HTTP request to target '{norm_url}' timed out after 12 seconds."
            result["recommendations"].append("Verify application is running and accessible over the network.")
        except Exception as http_err:
            result["blocking_status"] = "HTTP_PROBE_ERROR"
            result["blocking_reason"] = f"HTTP connection failed: {str(http_err)}"
            result["recommendations"].append("Check target URL scheme and web server availability.")

        return result

    async def _test_tcp_connection(self, host: str, port: int, timeout: float = 3.0) -> bool:
        try:
            _, writer = await asyncio.wait_for(
                asyncio.open_connection(host, port),
                timeout=timeout
            )
            writer.close()
            await writer.wait_closed()
            return True
        except Exception:
            return False

    def _detect_waf_signatures(self, headers: Dict[str, str], body: str) -> (bool, str):
        headers_lower = {k.lower(): str(v).lower() for k, v in headers.items()}
        body_lower = body.lower()

        for waf_name, sigs in self.WAF_SIGNATURES.items():
            for sig in sigs:
                if "header" in sig:
                    h_val = headers_lower.get(sig["header"], "")
                    if h_val and re.search(sig["pattern"], h_val, re.IGNORECASE):
                        return True, waf_name
                elif "body" in sig:
                    if re.search(sig["body"], body_lower, re.IGNORECASE):
                        return True, waf_name
        return False, "None"
